<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.56.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElevatorSimulator.Core\ElevatorSimulator.Core.csproj" />
    <ProjectReference Include="..\ElevatorSimulator.Simulation\ElevatorSimulator.Simulation.csproj" />
    <ProjectReference Include="..\ElevatorSimulator.Infrastructure\ElevatorSimulator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
